numoflabs = input("Enter the number of labs completed:")
numquizz = input("Enter the number of labs completed:")
numgrA1 = input("Enter grade for Assignment 1:")
numgrA2 = input("Enter grade for Assignment 2:")
numgrA3 = input("Enter grade for Assignment 3:")
numgrA4 = input("Enter grade for Assignment 4:")
grMT1 = input("Enter grade for Midterm 1:")
grMT2 = input("Enter grade for Midterm 2:")
grFE = input("Enter grade for Midterm 1:")
grEprep = input("Enter grade for Midterms and Final Preparation:")
labgr = ((numoflabs/6)*100*0.2)
quizzgr = ((numquizz/6)*100*0.15)
assigr = ((numgrA1 + numgrA2 + numgrA3 + numgrA4)*0.16)
grMTT = ((grMT1 + grMT2)*0.25)
grFET = (grFE*0.18)
grEprepT = (grEprep*0.06)
Tgrade = (labgr + quizzgr + assigr + grMTT + grFET + grEprepT)
print("Your Grade is: ", + str(round(grade)))
