numoflabs = float(input("Enter the number of labs completed: "))
numquizz = float(input("Enter the number of quizzes completed: "))
numgrA1 = float(input("Enter grade for Assignment 1: "))
numgrA2 = float(input("Enter grade for Assignment 2: "))
numgrA3 = float(input("Enter grade for Assignment 3: "))
numgrA4 = float(input("Enter grade for Assignment 4: "))
grMT1 = float(input("Enter grade for Midterm 1: "))
grMT2 = float(input("Enter grade for Midterm 2: "))
grFE = float(input("Enter grade for Final Exam: "))
grEprep = float(input("Enter grade for Midterms and Final Preparation: "))
labgr = ((numoflabs/6)*100*0.2)
quizzgr = ((numquizz/6)*100*0.15)
assigr = (((numgrA1 + numgrA2 + numgrA3 + numgrA4)/4)*0.16)
grMTT = (((grMT1 + grMT2)/2)*0.25)
grFET = (grFE*0.18)
grEprepT = (grEprep*0.06)
Tgrade = (labgr + quizzgr + assigr + grMTT + grFET + grEprepT)
print("Your Grade is:", round(Tgrade))
